dataset: ${dataset}
batch_size: ${training.batch_size}
num_workers: ${system.num_workers}
seed: ${seed}
training_method: centralized
train_splits: {'train': 0.9, 'val': 0.1}
aws_profile: null
s3_bucket_path: null
use_threads: null
norm: standrad #minmax #standard
kmeans_kwargs: {'n_clusters': 6}
upper_bound_scale: 0.1
lower_bound_scale: 0.1
val_batch_size: ${training.val_batch_size}
test_batch_size: ${training.test_batch_size}
num_train: null
num_val: null
num_test: null
