dataset: ${dataset}
batch_size: ${training.batch_size}
num_workers: ${system.num_workers}
seed: ${seed}
training_method: centralized
max_trajectory_length: null
aws_profile: null
s3_bucket_path: null
use_threads: null
val_batch_size: ${training.val_batch_size}
test_batch_size: ${training.test_batch_size}
num_train: null
num_val: null
num_test: null
text_labels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
display_labels: ['aedes_female', 'aedes_male', 'fruit_flies', 'house_flies', 'quinx_female', 'quinx_male', 'stigma_female', 'stigma_male', 'tarsalis_female', 'tarsalis_male']