batch_size: ${training.batch_size}
num_workers: ${system.num_workers}
training_method: federated
partition: iid
balanced: True
train_splits: [0.95, 0.05]
num_clients: 100
unbalanced_sigma: null # if false 1.0 >= .. > 0.0
seed: ${seed}
val_batch_size: ${training.val_batch_size}
test_batch_size: ${training.test_batch_size}
