epochs: 500
batch_size: 16
val_batch_size: ${training.batch_size}
test_batch_size: ${training.batch_size}
learning_rate: 0.005 #0.01
fast_dev: False
precision: 32
devices: null
multi_gpu_training: false
