dataset: ${dataset}
batch_size: ${training.batch_size}
num_workers: ${system.num_workers}
seed: ${seed}
training_method: centralized
max_trajectory_length: 1024
aws_profile: null
s3_bucket_path: null
use_threads: null
val_batch_size: ${training.val_batch_size}
test_batch_size: ${training.test_batch_size}
num_train: null
num_val: null
num_test: null
text_labels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
display_labels: ['1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']