epochs: 1000
batch_size: 16
val_batch_size: ${training.batch_size}
test_batch_size: ${training.batch_size}
learning_rate: 0.01
fast_dev: False
precision: 32
device: null
multi_gpu_training: False
log_every_n_steps: 10