epochs: 500
batch_size: 32
val_batch_size: ${training.batch_size}
test_batch_size: ${training.batch_size}
learning_rate: 0.01 #0.01
optimizer:
  name: sgd
  momentum: 0.5
  weight_decay: 1e-04
fast_dev: False

