training_method: 'centralized'
train_split_index: 0
aws_profile: null
s3_bucket_path: null
use_threads: null
num_train: null # 10000
num_val: null 
num_test: null
instance: null #'2024-10-17_14:19:55'
batch_size: ${training.batch_size}
num_workers: 0
text_labels: [0, 1, 2, 3, 4, 5, 6, 7]
pad_sequence: True
display_labels: [0, 1, 2, 3, 4, 5, 6, 7]
val_batch_size: ${training.val_batch_size}
test_batch_size: ${training.test_batch_size}
