training_method: centralized
train_split_index: 0
aws_profile: null
s3_bucket_path: null
use_threads: null
preprocessing_method: raindrop
min_seq_length: null
percentile_of_features_used: null
balance: random
upsample_percentage: 0.0
num_train: null # 10000
num_val: null 
num_test: null
instance: null #'2024-10-17_14:19:55'
batch_size: ${training.batch_size}
num_workers: 0
text_labels: [0, 1]
pad_sequence: True
display_labels: [0, 1]
val_batch_size: ${training.val_batch_size}
test_batch_size: ${training.test_batch_size}
